name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# defines a job (named test) and runs it on Ubuntu
jobs:
  test:
    runs-on: ubuntu-latest

# This starts a PostgreSQL container alongside our test runner.
# we will use this DB when our Django app runs migrations and tests.
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      SECRET_KEY: dummysecretkey
      DEBUG: True

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py migrate
          python manage.py test
